server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "youshallnotpass"
    plugins:
      - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.5" # Ini plugin wajib YouTube
    sources:
      youtube: true
      soundcloud: true
      http: true